services:
  chroma:
    image: chromadb/chroma:latest
    container_name: rag_chroma_server
    ports:
      - "8083:8000"
    volumes:
      - ./chroma_db:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_streamlit_app
    environment:
      - GROQ_API_KEY=your-groq-key
      - GROQ_MODEL=your-groq-model
      - MISTRALAI_API_KEY=your-mistral-key
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/data
