
services:
  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma_db:/data  
    ports:
      - "8081:8000"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    ports:
      - "8502:8501"
   
